openapi: 3.0.2
info:
  title: Frequently Asked Questions
  version: ''
  description: |
    ## OpenAPI specification

    We utilize OpenAPI, a standardized specification that defines and documents APIs. In essence, OpenAPI serves as a clear blueprint for our API's structure, endpoints, and data formats.
    An exciting advantage of OpenAPI is its capacity to assist you in effortlessly generating client libraries for various programming languages.
    
    Our OpenAPI specification is publicly accessible here: https://api.telgorithm.com/messaging/swagger/v1/swagger.json \
    Feel free to dive into the OpenAPI documentation for further insights: https://swagger.io/specification/

    ## OpenAPI Generator
    OpenAPI Generator generates code from an OpenAPI specification. It can create code for client libraries, server stubs, documentation and configuration.
    
    There are a number of ways to use OpenAPI Generator. Installing OpenAPI Generator's CLI tool allows users to generate all available generators from the command line. Learn more: https://openapi-generator.tech/docs/installation

    ## Generating Telgorithm's messaging client using OpenAPI Generator Online
    OpenAPI Generator Online allows you to generate clients without installing OpenAPI Generator locally. Web application is available at the following address: http://api.openapi-generator.tech/index.html
    1) Make a HTTP GET request to http://api.openapi-generator.tech/api/gen/clients using Rapidoc UI - click on "GET /api/gen/clients" (Screenshot 1)
    <p align="center">
      <img src="/media/images/open_api_generator_screenshot_1.webp" alt="Screenshot 1" /><br>
      <i>Screenshot 1</i>
    </p>
    2) Click button "Try" (Screenshot 2)
    <p align="center">
      <img src="/media/images/open_api_generator_screenshot_2.webp" alt="Screenshot 2" /><br>
      <i>Screenshot 2</i>
    </p>
    3) In server response you will receive array of available clients for generation - find your's and copy to clipboard. (Screenshot 3)
    <p align="center">
      <img src="/media/images/open_api_generator_screenshot_3.webp" alt="Screenshot 3" /><br>
      <i>Screenshot 3</i>
    </p>
    4) Click on "Post /api/gen/clients/{language}" (Screenshot 4)
    <p align="center">
      <img src="/media/images/open_api_generator_screenshot_4.webp" alt="Screenshot 4"/><br>
      <i>Screenshot 4</i>
    </p>
    5) In "language" path parameter paste your client, copied on step 3 (Screenshot 5)
    <p align="center">
      <img src="/media/images/open_api_generator_screenshot_5.webp" alt="Screenshot 5" /><br>
      <i>Screenshot 5</i>
    </p>
    6) In body of request ("Example" textarea) put payload (screenshot 6)
    <p align="center">
      <img src="/media/images/open_api_generator_screenshot_6.webp" alt="Screenshot 6" /><br>
      <i>Screenshot 6</i>
    </p>
     ```json
      {
        "openAPIUrl": "https://api.telgorithm.com/messaging/swagger/v1/swagger.json",
        "options": {
            "packageName": "telgorithm"
        }
      }
      ```
    7) Click button "Try" and wait for client generation (around 10 seconds)
    8) You will receive a link for downloading generated client, just copy it and paste in browser URL address (Screenshot 7)
    <p align="center">
      <img src="/media/images/open_api_generator_screenshot_7.webp" alt="Screenshot 7" /><br>
      <i>Screenshot 7</i>
    </p>
    9) Use generated client in your application (Screenshot 8)
    <p align="center">
      <img src="/media/images/open_api_generator_screenshot_8.webp" alt="Screenshot 8" /><br>
      <i>Screenshot 8</i>
    </p>

         

